Build non-ambiguous monikers in crates with multiple targets
Previously, a crate which defined multiple targets would cause
ambiguous monikers to be built.

For instance when generating an SCIP index in a simple project with a
lib and a bin target:
```
scip-collision/
├── Cargo.toml
└── src/
    ├── lib.rs
    └── main.rs
```

main.rs:
```
struct S;

fn main() {}
```

lib.rs:
```
struct S;
```

`rust-analyzer scip scip-collision` complained with:
```
Duplicate symbols encountered:

src/lib.rs:0:0-1:0
  Duplicate symbol: rust-analyzer cargo scip-collision 0.1.0 crate/

src/lib.rs:0:7-0:8
  Duplicate symbol: rust-analyzer cargo scip-collision 0.1.0 S#
```

This fixes the ambiguity by adding the target type and name° to each
symbol's moniker. For the example above we now get these symbols:
- `rust-analyzer cargo scip-collision 0.1.0 bin/scip_collision/`
- `rust-analyzer cargo scip-collision 0.1.0 bin/scip_collision/S#`
- `rust-analyzer cargo scip-collision 0.1.0 bin/scip_collision/main().`
- `rust-analyzer cargo scip-collision 0.1.0 lib/`
- `rust-analyzer cargo scip-collision 0.1.0 lib/S#`

°: this doesn't add the name for lib, proc-macro and build script
targets because there's only one of each per Cargo package.