internal: Fix rustdoc quoting
GitHub actions are currently failing with:

    error: unresolved link to `cfg_attr`
       --> crates/ide-completion/src/context.rs:414:61
        |
    414 |     /// Set if we are inside the predicate of a #[cfg] or #[cfg_attr].
        |                                                             ^^^^^^^^ no item named `cfg_attr` in scope
        |
        = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
        = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

     Documenting ide v0.0.0 (/home/runner/work/rust-analyzer/rust-analyzer/crates/ide)
    error: could not document `ide-completion`

Use backticks to fix this.

AI disclosure: written with Claude Opus because it was marginally
faster.